name: Heroku Awake

on:
  schedule:
    - cron: "*/5 16-18 * * *"
  workflow_dispatch:
      
jobs:
    run:
        name: Ping
        runs-on: ubuntu-latest
        steps:
            - name: Ping
              run: |
                  sh -c "curl --silent https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/ > /dev/null 2>&1" 
