name: Heroku Awake

on:
  schedule:
    - cron: "*/30 5-21 * * *"
  workflow_dispatch:
      
jobs:
    run:
        name: Ping
        runs-on: ubuntu-latest
        steps:
            - name: Ping
              run: |
                  sh -c "curl --silent --fail https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/" 
