name: Update plots

on:
 #   push:
 #       branches:
 #           - main
    schedule:
        - cron: '0 */6 * * *'
    workflow_dispatch:

jobs:
    update-plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up python 3.7.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7.9
                  
            - name: Get pip cache dir
              id: pip-cache
              run: |
                echo "::set-output name=dir::$(pip cache dir)"
            - name: Cache pip
              uses: actions/cache@v2
              with:
                path: ${{ steps.pip-cache.outputs.dir }}
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
                  
            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Generate plots
              env: 
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
              run: |
                  python fetch.py
            - name: Refresh cache
              env:
                  DOMAIN: "68747470733a2f2f6d74746d616e746f76616e692e73332e65752d63656e7472616c2d312e616d617a6f6e6177732e636f6d2f6368617274732f6c61746573742d746f74616c2e706e673f"
              run: |
                  curl -X PURGE https://camo.githubusercontent.com/dd710f6566697cdd05551eb3c56920e668278f131e800fdce90784067fd1493c/${DOMAIN}
                  curl -X PURGE https://camo.githubusercontent.com/a7eb94147282aa9dadf723846ccaa40d8343352f26906954efff640a7a03b7fe/${DOMAIN}
                  curl -X purge https://camo.githubusercontent.com/c75d0698049eecf3670d6e3c23f514b7b02c8144c18c5d2f1a2d351a00849052/${DOMAIN}

